- name: Deploy Laravel API
  hosts: all
  become: yes

  vars:
    project_dir: /opt/laravel-api
    docker_image: "{{ docker_image | default('mpetronm/laravel-api:latest') }}"

  tasks:
    - name: Update system and install dependencies
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create app directory
      file:
        path: "{{ project_dir }}"
        state: directory
        mode: '0755'

    - name: Copy production docker-compose
      copy:
        src: docker-compose.prod.yml
        dest: "{{ project_dir }}/docker-compose.yml"

    - name: Pull latest image
      shell: |
        cd {{ project_dir }}
        docker-compose pull

    - name: Deploy containers
      shell: |
        cd {{ project_dir }}
        docker-compose down || true
        docker-compose up -d

    - name: Fix permissions and migrate DB
      shell: |
        cd {{ project_dir }}
        sleep 10
        docker-compose exec -T app chmod -R 777 storage bootstrap/cache
        docker-compose exec -T app php artisan key:generate || true
        docker-compose exec -T app php artisan migrate --force || true

    - name: Health Check
      uri:
        url: http://localhost/api/productos
        method: GET
        status_code: 200
        timeout: 30
      register: health_check
      until: health_check.status == 200
      retries: 5
      delay: 10
      ignore_errors: yes
