- name: Deploy Laravel API
hosts: all
become: true

tasks:
  - name: Create app directory
    file:
      path: /opt/laravel-api
      state: directory
      mode: '0755'

  - name: Copy docker-compose file
    copy:
      src: ../docker-compose.prod.yml
      dest: /opt/laravel-api/docker-compose.yml

  - name: Pull latest Docker image
    shell: docker-compose pull
    args:
      chdir: /opt/laravel-api
    environment:
      DOCKER_IMAGE_NAME: ""{{ docker_image }}""

  - name: Start containers
    shell: docker-compose down && docker-compose up -d
    args:
      chdir: /opt/laravel-api
    environment:
      DOCKER_IMAGE_NAME: ""{{ docker_image }}""

  - name: Fix permissions and Migrate DB
    shell: |
      sleep 10
      docker-compose exec -T app chmod -R 777 storage bootstrap/cache
      docker-compose exec -T app php artisan migrate --force
    args:
      chdir: /opt/laravel-api
